name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
      DB_HOST: localhost
      DB_PORT: "5432"
      DB_USER: indoor_radio
      DB_PASSWORD: indoor_radio_password
      DB_NAME: indoor_radio_test
      DB_NAME_TEST: indoor_radio_test
      DB_SSL_MODE: disable
    services:
      postgres:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: >-
          --health-cmd "pg_isready -U postgres -h 127.0.0.1"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev postgresql-client

      - name: Bundle install
        run: bundle install --jobs 4 --retry 3

      - name: Prepare database
        run: |
          bundle exec rails db:prepare

      - name: Smoke test Rails boot
        run: |
          bundle exec rails about

      - name: Run tests (if present)
        run: |
          if [ -f bin/rails ]; then
            # Run minitest if present; otherwise this will no-op successfully
            bundle exec rails test || true
          fi

